### ISSUE TITLE
HTTP Proxy for rewrite rules

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#37]
Currently the platform is configured with the following configuration for routing requests from Internet

->Internet user reachs  `*.waziup.io:80`
->OpenStack HA Proxy forwards `*.waziup.io:80` on `192.168.10.101:30999`
->Kubernetes Ingress controller running in a pod on `192.168.10.101:30999` forwards to corresponding pod
-> pod receives the request

The Ingress controller allows to expose pods on nice URL such as `controller.waziup.io`, using a configuration file:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: controller
  namespace: waziup
spec:
  rules:
  - host: controller.waziup.io
    http:
      paths:
      - path: /
        backend:
          serviceName: controller
          servicePort: 8080
```

This simple language allows to expose pods. But it doesn't allow to make rewrite rules, as needed for the waziup API. #23
