### ISSUE TITLE
New historical data API

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#68]
Opening this issue just to brainstorm on the historical data API.
Now the format is: 
```
$ curl -S -s 'http://127.0.0.1:8080/?colName=sth_/TEST_Sensor1_SensingDevice'

[
  {
    "_id": "58402ede2ab79c00079ae256",
    "recvTime": "2016-12-01T14:08:24.508Z",
    "attrName": "temperature",
    "attrType": "Number",
    "attrValue": "23"
  },
  {
    "_id": "58402f262ab79c00079ae257",
    "recvTime": "2016-12-01T14:09:37.413Z",
    "attrName": "temperature",
    "attrType": "Number",
    "attrValue": "27"
  }
]
```
The argument 'colName' contains a mix of service path (/TEST), sensor name (Sensor1) and type (SensingDevice).

We probably should adopt a format closer to Orion API.
See this question:
http://stackoverflow.com/questions/40790097/retrieve-historical-data-with-fiware-orion-cygnus

I also opened a spec file: https://github.com/Waziup/Platform/blob/master/broker/history/history_spec.md

**Comment by DiopBabacarEdu** [comment]
Historical data using sth-comet
---------
docker-compose.yml

`````
version: '2'

services:

  mongo:
    image: waziup/mongodb:latest
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    command: --nojournal

  orion:
    image: waziup/orion:latest
    hostname: orion
    container_name: orion
    ports:
      - "1026:1026"
    command: -dbhost mongo

  cygnus:
    image: waziup/cygnus
    hostname: cygnus
    container_name: cygnus
    links:
      - orion
      - mongo
    expose:
      - "5050"
    ports:
      - "5050:5050"

  fiware-sth-comet:
    image: telefonicaiot/fiware-sth-comet
    hostname: sth-comet
    container_name: sth-comet
    links:
      - mongo
    ports:
      - "8666:8666"
    environment:
      - STH_HOST=0.0.0.0
      - DB_URI=mongo:27017

`````

Command to execute .yml file :
-----
`````
$ docker-compose up
`````
Subscribing the STH component instance to the entity attributes of interest by sending a request below to the Orion Context Broker instance  :
---
Requesting without duration and throtting values ...
`````
curl localhost:1026/v1/subscribeContext -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Fiware-Service: ' --header 'Fiware-ServicePath: /' -d @- <<EOF
{
    "entities": [
        {
            "type": "Room",
            "isPattern": "false",
            "id": "Room1"
        }
    ],
    "attributes": [
        "humidity"
],
    "reference": "http://localhost:8666/notify",
    "notifyConditions": [
        {
            "type": "ONCHANGE",
            "condValues": [
                "humidity"
            ]
        }
    ]
    
}
EOF
`````

New Issues?
----
Which values for duration and throtting format on curl subscriptions request?
`````
curl localhost:1026/v1/subscribeContext -s -S --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Fiware-Service: ' --header 'Fiware-ServicePath: /' -d @- <<EOF
{
    "entities": [
        {
            "type": "Room",
            "isPattern": "false",
            "id": "Room1"
        }
    ],
    "attributes": [
        "humidity"
],
    "reference": "http://localhost:8666/notify",
    "duration": "<duration>",
    "notifyConditions": [
        {
            "type": "ONCHANGE",
            "condValues": [
                "humidity"
            ]
        }
    ],
"throttling": "<throttling>"
    
}
EOF
`````
